arthouse/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from home import views




urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home, name='home'),
    url(r'^', include('contacts.urls', namespace='contacts')),
    url(r'^', include('gallery.urls', namespace='gallery')),
    url(r'^', include('prices.urls', namespace='prices')),
    url(r'^', include('projects.urls', namespace='projects')),
    url(r'^', include('aboutus.urls', namespace='about_us')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]
if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prices/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^prices/$', prices, name='prices'),
    url(r'^prices/order/$', OrderFormView.as_view(), name='order'),
]

projects/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^projects/$', projects, name='projects'),
    url(r'^project/(?P<id>\d+)/$', project_detail, name='project_detail'),
    url(r'^category/(?P<id>\d+)/$', projects_in_category, name='projects_in_category'),
]

projects/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.urls import reverse
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFit
5

class ProjectCategory(models.Model):
    name = models.CharField(max_length=128, blank=True, null=True, default=None)
    title = models.CharField(max_length=128, blank=True, null=True, default=None)
    short_description = RichTextUploadingField(blank=True, null=True, default=None)
    description = RichTextUploadingField(blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    update = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return ("%s") % self.name

    def get_absolute_url(self):
        return reverse('projects:projects_in_category', kwargs={'id': self.id})

    class Meta:
        verbose_name = 'Категорія проекту'
        verbose_name_plural = 'Категорії проектів'


class Project(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    category = models.ForeignKey(ProjectCategory, blank=True, null=True, default=None, on_delete=models.CASCADE)
    short_description = RichTextUploadingField(blank=True, null=True, default=None)
    description = RichTextUploadingField(blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    update = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return ("%s") % (self.name)

    def get_absolute_url(self):
        return reverse('projects:project_detail', kwargs={'id': self.id})

    class Meta:
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекти'


class ProjectImage(models.Model):
    project = models.ForeignKey(Project, blank=True, null=True, default=None, on_delete=models.CASCADE)

    image = models.ImageField(upload_to="products_images/", blank=True, null=True, default=None)

    image_thumbnail = ImageSpecField(source='image',
                                      processors=[ResizeToFit(700)],
                                      format='JPEG',
                                      options={'quality': 60})

    is_active = models.BooleanField(default=True)
    is_main = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    update = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.project.name

    class Meta:
        verbose_name = 'Фото'
        verbose_name_plural = 'Фотки'


class PageProjectsDescription(models.Model):
    title = models.CharField(max_length=128, blank=True, null=True)
    sub_title = RichTextUploadingField(max_length=128, blank=True, null=True)
    short_description = RichTextUploadingField(blank=True, null=True, default=None)
    description = RichTextUploadingField(blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    update = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Опис сторінки проекти'
        verbose_name_plural = 'Опис сторінки проектиу'

projects/views.py
from django.shortcuts import render, get_object_or_404
from urllib.parse import quote_plus
from .models import Project, ProjectCategory, PageProjectsDescription

def projects(request):
	categories = ProjectCategory.objects.filter(is_active=True)

	title_description_model = PageProjectsDescription.objects.filter(is_active=True)[0]
	print(title_description_model)
	title = title_description_model.title
	short_description = title_description_model.short_description
	description = title_description_model.description
	
	projects = Project.objects.filter(is_active=True)
	# category_title = ProjectCategory.
	# category_description
	# print(projects)
	# if project.category.name == 'Проекти':
	# 	category_title = 
	# 	category_description
	context = {
			'categories': categories,
			'title': title,
			'short_description':short_description,
			'description': description,
			'projects': projects,
		}

	return render(request, 'projects/projects.html', context)

def project_detail(request, id=None):
	categories = ProjectCategory.objects.filter(is_active=True)
	project = get_object_or_404(Project, id=id)
	share_string = quote_plus("Проект ") + quote_plus(project.name)
	if project.short_description:
		share_string = quote_plus("Проект ") + quote_plus(project.name) + quote_plus(" ") + quote_plus(project.short_description)
	context = {
			'categories': categories,
			'project': project,
			'share_string': share_string,
		}

	return render(request, 'projects/project_detail.html', context)


def projects_in_category(request, id=None):
	categories = ProjectCategory.objects.filter(is_active=True)
	category = get_object_or_404(ProjectCategory, id=id)
	projects_in_category = Project.objects.filter(is_active=True, category_id = id)
	context = {
			'categories': categories,
			'category':category,
			'projects_in_category': projects_in_category,
		}

	return render(request, 'projects/projects_in_category.html', context)

templates/projects/project_detail.html
{% extends 'base.html' %}

{% block head_title %}Проекти | {{ block.super }} {% endblock %}


{% block sub_nav_bar %}

{% include 'projects/projects_navbar.html' %}

{% endblock sub_nav_bar %}



{% block breadcrumb %}

<div class="container">
	<nav aria-label="breadcrumb">
	  <ol class="breadcrumb">
	    <li class="breadcrumb-item"><a href="/">Головна</a></li>
	    <li class="breadcrumb-item"><a href="{% url 'projects:projects' %}">Проекти</a></li>
	    <li class="breadcrumb-item"><a href="{{ project.category.get_absolute_url }}">{{ project.category.name }}</a></li>
	    <li class="breadcrumb-item active" aria-current="page">{{ project.name }}</li>
	  </ol>
	</nav>
</div>

{% endblock breadcrumb %}



{% block content %}
<!-- <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/uk_UA/sdk.js#xfbml=1&version=v3.0';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script> -->

<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<!-- Розмістіть цей тег у заголовку або перед закриваючим тегом тексту. -->
<script src="https://apis.google.com/js/platform.js" async defer>
  {lang: 'uk'}
</script>

	<div class="container">
		<div class="row">
			<div class="col-md-12 margin-bottom-65px">
				{% if project.name %}
				<h1 class="text-center">{{ project.name }}</h1>
				{% endif %}
				{% if project.short_description %}
                <p>{{ project.short_description|safe }} </p>
                {% endif %}
				{% if project.description %}
	            <div class="content hideContent">
	                <p>{{ project.description|safe }}</p>
	            </div>
	            <div class="show-more">
	                <a href="#" class="more-link">Детальніше</a>
	            </div>
	            {% endif %}
			</div>

			<div class="col-md-6">
			{% for img in project.projectimage_set.all|slice:"::2" %}
				<div class="img-div img-margin-booton-15px">
					<a data-fancybox="gallery" data-options='{"buttons": ["zoom", "slideShow", "fullScreen", "share","close"]}' data-caption="{{ project.name }}" href="{{ img.image.url }}" class="outline-focus-none">
	                  <!-- <img src="{{ img.image.url }}" alt="{{ img.image.name }}" class="outline-focus-none thumbnail-img img-fluid img-zoom img-padding-booton-15px"> -->
	                  {% if img.image %}
	                  	<img class="card-img-top-border-radius-0 img-zoom" src="{{ img.image_thumbnail.url }}" alt="{{ project.name }}">
	                  {% endif %}
	                </a>
           		</div>

					<!-- <div class="project-img">
						<img class="img-fluid" src="{{ img.image.url }}" alt="Project image">

						<div class="share-btn">
			                <button type="button" class="btn btn-primary">Share</button>
			            </div>

					</div> -->				
			{% endfor %}
			</div>

			<div class="col-md-6">
			{% for img in project.projectimage_set.all|slice:"1::2" %}
				<div class="img-div img-margin-booton-15px">
				<a data-fancybox="gallery" data-options='{"buttons": ["zoom", "slideShow", "fullScreen", "share","close"]}' data-caption="{{ project.name }}" href="{{ img.image.url }}" class="outline-focus-none">
                  <!-- <img src="{{ img.image.url }}" alt="{{ img.image.name }}" class="outline-focus-none thumbnail-img img-fluid img-zoom img-padding-booton-15px "> -->
                  {% if img.image %}
                  	<img class="card-img-top-border-radius-0 img-zoom" src="{{ img.image_thumbnail.url }}" alt="{{ project.name }}">
                  {% endif %}
                </a>
                </div>
					<!-- <div class="project-img">
						<img class="img-fluid" src="{{ img.image.url }}" alt="Project image">

						<div class="share-btn">
			                <button type="button" class="btn btn-primary">Share</button>
			            </div>

					</div> -->				
			{% endfor %}
			</div>

		</div>
		<div class="social-likes-title">Поділитися проектом</div>
		<div class="row row-social-likes">
			<div class="col-md-3">
				<a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}" target="_blank">
					Share on Facebook
				</a>
				<!-- <div class="fb-share-button" data-href="https://developers.facebook.com/docs/plugins/" data-layout="button" data-size="small" data-mobile-iframe="true"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Поширити</a></div> -->

			</div>

			<div class="col-md-3">
				<a href="https://twitter.com/home?status={{ share_string }}%20%20{{ request.build_absolute_uri }}" target="_blank">
					Share on Twitter
				</a>
				<!-- <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-show-count="false">Tweet</a> -->
			</div>

			<div class="col-md-3">
				<a href='https://plus.google.com/share?url={{ request.build_absolute_uri }}' target="_blank">
					Share on Google+ 
				</a>

				<!-- Розмістіть цей тег у місці, де потрібно відтворити кнопка "Поділитися" -->
				<!-- <div class="g-plus" data-action="share"></div> -->
				
			</div>
			<div class="col-md-3">
				<a data-pin-do="buttonBookmark" href="//www.pinterest.com/pin/create/button" target="_blank"><!-- <img src="//assets.pinterest.com/images/pidgets/pinit_fg_en_rect_gray_20.png" /> --></a>
			</div>
		</div>
	</div>

{% endblock content %}

templates/projects/projects.html
{% extends 'base.html' %}

{% block head_title %} {{ title }} | {{ block.super }} {% endblock %}


{% block sub_nav_bar %}

{% include 'projects/projects_navbar.html' %}

{% endblock sub_nav_bar %}


{% block breadcrumb %}

<div class="container">
	<nav aria-label="breadcrumb">
	  <ol class="breadcrumb">
	    <li class="breadcrumb-item"><a href="/">Головна</a></li>
	    <li class="breadcrumb-item active" aria-current="page">Проекти</li>
	  </ol>
	</nav>
</div>

{% endblock breadcrumb %}


{% block content %}


	<div class="container">
		<div class="row">
			<div class="col-md-12">
				{% if title %}
				<h1 class="text-center page__title">{{ title }}</h1>
				{% endif %}
				{% if description %}
				<p>{{ short_description|safe }}</p>
				{% endif %}
				{% if description %}
	            <div class="content hideContent">
	                <p>{{ description|safe }}</p>
	            </div>
	            <div class="show-more">
	                 <a href="#" class="more-link margin-bottom-65px">Детальніше</a>
	            </div>
	            {% endif %}
			</div>
		</div>
	</div>
            


	<div class="container-fluid">
		<div class="row">
			{% for project in projects %}
				<div class="col-md-3 col-md-3-padding-0">
			      	{% for obj in project.projectimage_set.all %}
				      	{% if obj.is_main %}
				        <div class="img-div">
				        	<a href="{{ project.get_absolute_url }}">
				        		<img class="card-img-top card-img-top-border-radius-0 img-zoom" src="{{ obj.image.url }}" alt="Card image cap">
				        	</a>
				        </div>
				        {% endif %}
				    {% endfor %}

			        <div class="project__title">
			          <a href="{{ project.get_absolute_url }}"><p>{{ project.name }}</p></a>
			        </div>
	        	</div>
	    	{% endfor %}
		</div>
	</div>


{% endblock content %}

templates/projects/projects_in_category.html
{% extends 'base.html' %}

{% block head_title %}Проекти | {{ block.super }} {% endblock %}


{% block sub_nav_bar %}

{% include 'projects/projects_navbar.html' %}

{% endblock sub_nav_bar %}



{% block breadcrumb %}
<div class="container">
	<nav aria-label="breadcrumb">
	  <ol class="breadcrumb">
	    <li class="breadcrumb-item"><a href="/">Головна</a></li>
	    <li class="breadcrumb-item"><a href="{% url 'projects:projects' %}">Проекти</a></li>
	    <li class="breadcrumb-item active" aria-current="page">{{ category.name }}</li>
	  </ol>
	</nav>
</div>

{% endblock breadcrumb %}



{% block content %}
    

    <div class="container margin-bottom-65px">
		<div class="row">
			<div class="col-md-12">
				{% if category.name %}
				<h1 class="text-center page__title">{{ category.name }}</h1>
				{% endif %}
				{% if category.short_description %}
                <p>{{ category.short_description|safe }} </p>
                {% endif %}
				{% if category.description %}
	            <div class="content hideContent">
	                <p>{{ category.description|safe }}</p>
	            </div>
	            <div class="show-more">
	                <a href="#" class="more-link">Детальніше</a>
	            </div>
	            {% endif %}
			</div>
		</div>
	</div>

	<div class="container-fluid">
		<div class="row">
			{% for project in projects_in_category %}
				<div class="col-md-3 col-md-3-padding-0">
			      	{% for obj in project.projectimage_set.all %}
				      	{% if obj.is_main %}
				        <div class="last-projects-img-size img-div">
				        	<a href="{{ project.get_absolute_url }}">
				        		<img class="card-img-top image-resize card-img-top-border-radius-0 img-zoom" src="{{ obj.image.url }}" alt="Card image cap">
				        	</a>
				        </div>

					    <div class="project__title">
				          <a href="{{ project.get_absolute_url }}"><p>{{ project.name }}</p></a>
				        </div>				        	
				        
				        {% endif %}
				    {% endfor %}
	        	</div>
	    	{% endfor %}
		</div>
	</div>


{% endblock content %}

templates/projects/projects_navbar.html
<nav class="navbar navbar-expand-md sub-nav-bar-sticky main-background-color d-none d-md-block d-xl-block">
  <div class="container">

        <ul class="navbar-nav mx-auto">
          {% for category in categories %}
          <li class="nav-item">
            <a class="nav-link" href="{{ category.get_absolute_url }}">{{ category.name }}</a>
          </li>
          {% endfor %}
        </ul>
    </div>
  </nav>