arthouse/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from home import views




urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home, name='home'),
    url(r'^', include('contacts.urls', namespace='contacts')),
    url(r'^', include('gallery.urls', namespace='gallery')),
    url(r'^', include('prices.urls', namespace='prices')),
    url(r'^', include('projects.urls', namespace='projects')),
    url(r'^', include('aboutus.urls', namespace='about_us')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]
if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prices/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^prices/$', prices, name='prices'),
    url(r'^prices/order/$', OrderFormView.as_view(), name='order'),
]

prices/models.py
from phonenumber_field.modelfields import PhoneNumberField
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models


class OrderModel(models.Model):
    order_name = models.CharField("Послуга", max_length=32, blank=False, null=False, default=None)
    client_name = models.CharField("Ім'я", max_length=128, blank=False, null=False, default=None)
    phone_number = PhoneNumberField("Номер телефону", max_length=128, blank=False, null=False, default=None)
    email = models.EmailField(max_length=128, blank=True, null=True, default=None)
    coment = models.TextField("Коментар", blank=True, null=True, default=None)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    update = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return ("%s") % self.client_name

    class Meta:
        verbose_name = 'Замовлення'
        verbose_name_plural = 'Замовлення'

class Prices(models.Model):
    title = models.CharField(max_length=128, blank=True, null=True, default=None)
    short_description = RichTextUploadingField(blank=True, null=True, default=None)
    description = RichTextUploadingField(blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    update = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return ("%s") % self.title

    class Meta:
        verbose_name = 'Розділ "Ціни"'
        verbose_name_plural = 'Розділи "Ціни"'


class PriceCategory(models.Model):
    name = models.CharField(max_length=128, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    update = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return ("%s") % self.name

    class Meta:
        verbose_name = 'Категорія ціни'
        verbose_name_plural = 'Категорії цін'


class ProiceCategoryDescription(models.Model):
    category = models.ForeignKey(PriceCategory, blank=True, null=True, default=None, on_delete=models.CASCADE)
    title = models.CharField(max_length=128, blank=True, null=True, default=None)
    description = RichTextUploadingField(blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    update = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return ("%s") % self.title

    class Meta:
        verbose_name = 'Опис категорії ціни'
        verbose_name_plural = 'Описи категорії ціни'

prices/forms.py
from django import forms
from phonenumber_field.widgets import PhoneNumberPrefixWidget
from .models import OrderModel

class OrderForm(forms.ModelForm):
    class Meta:
        model = OrderModel
        fields = [
        	"order_name",
        	"client_name",
        	"phone_number",
        	"email",
        	"coment"
        ]
        widgets = {
            'content': forms.Textarea(attrs={'cols': 80, 'rows': 20}),
            # 'phone_number': PhoneNumberPrefixWidget(),
        }

prices/views.py
from django.http import JsonResponse
from django.views.generic import FormView
from django.shortcuts import render, get_object_or_404
from .forms import OrderForm
from .models import Prices, PriceCategory, ProiceCategoryDescription, OrderModel

def prices(request):
	prices = Prices.objects.filter(is_active=True)[0]

	title = prices.title
	short_description = prices.short_description
	description = prices.description

	price_categorys = PriceCategory.objects.filter(is_active=True)
	price_category_description = ProiceCategoryDescription.objects.filter(is_active=True)
	context = {
			'title': title,
			'description': description,
			'short_description': short_description,
			'price_categorys':price_categorys,
			'price_category_description':price_category_description,
		}

	return render(request, 'prices/prices.html', context)


class OrderFormView(FormView):
    form_class = OrderForm
    template_name  = 'prices/order_form.html'
    success_url = '/prices/'


    def form_invalid(self, form):
        response = super(OrderFormView, self).form_invalid(form)
        if self.request.is_ajax():
            
            return JsonResponse(form.errors, status=400)
        else:
            return response

    def form_valid(self, form):
        response = super(OrderFormView, self).form_valid(form)
        form.save()
        if self.request.is_ajax():
            print(form.cleaned_data)
            data = {
                'message': "Successfully submitted form data."
            }
            return JsonResponse(data)
        else:
            return response

templates/prices/order_form.html
<div class="form-container form-group">
  {% if form.errors.non_field_errors %}
    {{ form.errors.non_field_errors }}
  {% endif %}
  <form class='my-ajax-form' method='POST' action="{% url 'prices:order' %}">{% csrf_token %}
    {{ form.as_p }}
    <span class="text-danger phone-error"></span><br>
    <span class="text-danger email-error"></span>
    <div class="text-right"><input class="button button_white-grey" type="submit" value="Відпрвавити"></div>
  </form>
</div>


{% load static %}
<script src="{% static 'js/intlTelInput.js' %}"></script>
<script src="{% static 'js/utils.js' %}"></script>
<script>
    $("#id_phone_number").intlTelInput({placeholderNumberType: "off", initialCountry: "UA", preferredCountries: [] })
    var countryData = $("#id_phone_number").intlTelInput("getSelectedCountryData");
    var int_code = countryData.dialCode
    $("#id_phone_number").intlTelInput("setNumber", "+"+int_code);

    $("#id_phone_number").on("countrychange", function(e, countryData) {
    var int_code = countryData.dialCode
    $("#id_phone_number").intlTelInput("setNumber", "+"+int_code);
    });
</script>

<script>
$(document).ready(function(){
    // var service = $(".btn-order:visited").attr("data-service");
    // console.log(service)
    $("#id_order_name").val(service);
    var $myForm = $('.my-ajax-form')
    $myForm.submit(function(event){
        event.preventDefault()
        var $formData = $(this).serialize()
        var $thisURL = $myForm.attr('action') // || window.location.href // or set your own url
        $.ajax({
            method: "POST",
            url: $thisURL,
            data: $formData,
            success: handleFormSuccess,
            error: handleFormError,
        })
    })

    function handleFormSuccess(data, textStatus, jqXHR){
        console.log(data)
        console.log(textStatus)
        console.log(jqXHR)
        var instance = $.fancybox.getInstance();
        console.log(instance)
        instance.close();
        $.fancybox.open('<div class="message"><h2>Дякуємо!</h2><p>Ваше замовлення прийнято!</p></div>');
        // $myForm[0].reset(); // reset form data
    }

    function handleFormError(jqXHR, textStatus, errorThrown){
        console.log(jqXHR);
        console.log(textStatus);
        console.log(errorThrown);
        if (jqXHR.responseJSON.phone_number){
          $('#id_phone_number').addClass('erorr-input-field');
          
          if (!$(".phone").length){
            var phone_text_error  = "<span class='erorr-input-field phone'> Введіть вірний телефон</span>"
            $('label[for="id_phone_number"]').after(phone_text_error)
          }
          // $('.phone-error').text(jqXHR.responseJSON.phone_number[0]);
        } else {
            $('#id_phone_number').removeClass('erorr-input-field')
            $(".phone").remove()
        }

        if (jqXHR.responseJSON.email){
          $('#id_email').addClass('erorr-input-field');
          if (!$(".email").length){
              var email_text_error  = "<span class='erorr-input-field email'> Введіть вірну електронну адресу</span>"
              $('label[for="id_email"]').after(email_text_error)
          }
          // $('.email-error').text(jqXHR.responseJSON.email[0]);
        } else {
            $('#id_email').removeClass('erorr-input-field')
            $(".email").remove()
        }
    }
})
</script>

templates/prices/order_form_old.html
{% load static %}
<div class="form-container">
	<h1>Форма Замовлення</h1>
<form class="my-ajax-form" method="POST" action="{% url 'prices:order' %}">{% csrf_token %}
  <div class="form-group">
    <label for="service">Замовлення послуги</label>
    <input type="text" name="{{ form.order_name.name }}" class="form-control" id="service" value="Послуга">
  </div>
  <div class="form-group">
    <label for="{{ form.client_name.id_for_label }}">І'мя</label>
    <input type="text" class="form-control" name="{{ form.client_name.name }}" id="{{ form.client_name.id_for_label }}" placeholder="І'мя">
  </div>
  <div class="form-group">
    <label for="{{ form.phone_number.id_for_label }}">Телефон</label>
    <input type="tel" name="{{ form.phone_number.name }}" id="{{ form.phone_number.id_for_label }}" class="form-control">
  </div>
  <div class="form-group">
    <label for="{{ form.email.id_for_label }}">Email address</label>
    <input type="email" name="{{ form.email.name }}" id="{{ form.email.id_for_label }}" class="form-control" placeholder="електронна адреса">
  </div>
  <div class="form-group">
    <label for="{{ form.coment.id_for_label }}">Коментар</label>
    <textarea name="{{ form.coment.name }}" cols="" rows="3" class="form-control" id="{{ form.coment.id_for_label }}"></textarea>
  </div>
  <!-- {{form.as_p}} -->

  <button type="submit" class="btn btn-primary">Відправити</button>
</form>
</div>




<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script> -->
<script src="{% static 'js/intlTelInput.js' %}"></script>
<script src="{% static 'js/utils.js' %}"></script>
<script>

  
	$("#{{ form.phone_number.id_for_label }}").intlTelInput({placeholderNumberType: "off", initialCountry: "UA", preferredCountries: [] })
	var countryData = $("#{{ form.phone_number.id_for_label }}").intlTelInput("getSelectedCountryData");
	var int_code = countryData.dialCode
	$("#{{ form.phone_number.id_for_label }}").intlTelInput("setNumber", "+"+int_code);

	$("#{{ form.phone_number.id_for_label }}").on("countrychange", function(e, countryData) {
	var int_code = countryData.dialCode
	$("#{{ form.phone_number.id_for_label }}").intlTelInput("setNumber", "+"+int_code);
	});
 
</script>

<script>
$(document).ready(function(){
    var $myForm = $('.my-ajax-form')
    $myForm.submit(function(event){
        event.preventDefault()
        var $formData = $(this).serialize()
        var $thisURL = $myForm.attr('action') || window.location.href // or set your own url
        $.ajax({
            method: "POST",
            url: $thisURL,
            data: $formData,
            success: handleFormSuccess,
            error: handleFormError,
        })
    })

    function handleFormSuccess(data, textStatus, jqXHR){
        console.log(data)
        console.log(textStatus)
        console.log(jqXHR)
        $myForm[0].reset(); // reset form data
    }

    function handleFormError(jqXHR, textStatus, errorThrown){
        console.log(jqXHR)
        console.log(textStatus)
        console.log(errorThrown)
    }
})
</script>

templates/prices/prices.html
{% extends 'base.html' %}

{% block head_title %} {{ title }} | {{ block.super }} {% endblock %}


{% block breadcrumb %}

<div class="container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Головна</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ title }}</li>
    </ol>
  </nav>
</div>

{% endblock breadcrumb %}






{% block content %}

        <div class="container main-background-color page__container margin-bottom-65px">
        <div class="row">
          <div class="col-md-12">
                <h1 class="text-center page__title">{{ title }}</h1>
                {% if short_description %}
                <p>{{ short_description|safe }} </p>
                {% endif %}
                {% if description %}
                <div class="content hideContent">
                    <p>{{ description|safe }}</p>
                </div>
                <div class="show-more">
                    <a href="#" class="more-link">Детальніше</a>
                </div>
                {% endif %}

                {% if price_categorys %}
                <ul class="nav nav-pills" id="pills-tab" role="tablist">

                  {% for cat in price_categorys %}
                    {% if forloop.first %}
                    <li class="nav-item">
                      <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#{{ cat.name }}" role="tab" aria-controls="pills-home" aria-selected="true">{{ cat.name }}</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                      <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#{{ cat.name }}" role="tab" aria-controls="pills-profile" aria-selected="false">{{ cat.name }}</a>
                    </li>
                    {% endif %}
                  {% endfor %}
                </ul>

                <div class="tab-content" id="pills-tabContent">
                  {% for cat in price_categorys %}

                    {% if forloop.first %}
                    <div class="tab-pane animated active" id="{{ cat.name }}" role="tabpanel" aria-labelledby="pills-home-tab">
                      <div class="row">
                      {% for des in price_category_description %}
                        
                        {% if des.category == cat %}
                        <div class="col-md-6">
                        <h3>{{ des.title }}</h3>
                        <p>{{ des.description|safe }}</p>
                        <a data-fancybox data-type="ajax" data-src="{% url 'prices:order' %}" href="javascript:;" data-service="{{ des.title }}" class="btn btn-primary btn-order">Замовити</a>
                        </div>
                        {% endif %}
                        
                      {% endfor %}
                      </div>
                    </div>

                    {% else %}
                    <div class="tab-pane" id="{{ cat.name }}" role="tabpanel" aria-labelledby="pills-profile-tab">
                      <div class="row">
                      {% for des in price_category_description %}
                        
                        {% if des.category == cat %}
                        <div class="col-md-6">
                        <h3>{{ des.title }}</h3>
                        <p>{{ des.description|safe }}</p>
                        <a data-fancybox data-type="ajax" data-src="{% url 'prices:order' %}" href="javascript:;" data-service="{{ des.title }}" class="btn btn-primary btn-order">Замовити</a>
                        </div>
                        {% endif %}
                        

                      {% endfor %}
                      </div>
                    </div>

                    {% endif %}

                  {% endfor %}
                    </div>
                </div>
                {% endif %}

          </div>
        </div>



{% endblock content %}

{% block script %}
{% load static %}
<script src="{% static 'js/intlTelInput.js' %}"></script>
<script src="{% static 'js/utils.js' %}"></script>

<script type="text/javascript">
  $(document).ready(function(){
    $(".btn-order").on("click", function(){
      service = $(this).attr("data-service");
    })
  })
</script>

{% endblock script %}