arthouse/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from home import views




urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home, name='home'),
    url(r'^', include('contacts.urls', namespace='contacts')),
    url(r'^', include('gallery.urls', namespace='gallery')),
    url(r'^', include('prices.urls', namespace='prices')),
    url(r'^', include('projects.urls', namespace='projects')),
    url(r'^', include('aboutus.urls', namespace='about_us')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]
if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contacts/urls.py
from django.conf.urls import url
from .views import contacts

urlpatterns = [
    url(r'^contacts/$', contacts, name='contacts'),
]

prices/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^prices/$', prices, name='prices'),
    url(r'^prices/order/$', OrderFormView.as_view(), name='order'),
]

projects/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^projects/$', projects, name='projects'),
    url(r'^project/(?P<id>\d+)/$', project_detail, name='project_detail'),
    url(r'^category/(?P<id>\d+)/$', projects_in_category, name='projects_in_category'),
]

home/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models


class Carousel(models.Model):
	"""Adding imgs for main slider"""
	title = models.CharField(max_length=128, blank=True, null=True)
	img = models.ImageField(upload_to="carousel_images/")
	description = RichTextUploadingField(blank=True, null=True, default=None)
	is_active = models.BooleanField(default=True)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
	update = models.DateTimeField(auto_now=True, auto_now_add=False)

	def __str__(self):
		return self.title

	class Meta:
		verbose_name = 'Фото для слайдера'
		verbose_name_plural = 'Фото для слайдера'


class InteriorDesign(models.Model):
	title = models.CharField(max_length=128, blank=True, null=True)
	short_description = RichTextUploadingField(blank=True, null=True, default=None)
	description = RichTextUploadingField(blank=True, null=True, default=None)
	is_active = models.BooleanField(default=True)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
	update = models.DateTimeField(auto_now=True, auto_now_add=False)

	def __str__(self):
		return self.title

	class Meta:
		verbose_name = 'Дизайн інтерєру'
		verbose_name_plural = 'Дизайн інтерєру'


class FaviconImage(models.Model):
	name = models.CharField(max_length=128, blank=True, null=True)
	favicon = models.ImageField(upload_to="favicon/", blank=True, null=True, default=None)

	is_active = models.BooleanField(default=True)
	created = models.DateTimeField(auto_now_add=True, auto_now=False)
	update = models.DateTimeField(auto_now=True, auto_now_add=False)

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = 'Фавікон'
		verbose_name_plural = 'Фавікони'


# class LastProjects(models.Model):
# 	"""Adding imgs for maine slider"""
# 	title = models.CharField(max_length=128, blank=True, null=True)
# 	img = models.FileField()
# 	description = models.TextField(blank=True, null=True, default=None)
# 	is_active = models.BooleanField(default=True)
# 	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
# 	update = models.DateTimeField(auto_now=True, auto_now_add=False)

# 	def __str__(self):
# 		return self.title

home/views.py
from django.shortcuts import render

from .models import Carousel, InteriorDesign
from projects.models import Project


def home(request):
	title = 'Welcome'
	carousel_imgs = Carousel.objects.filter(is_active=True)
	home_page_content = InteriorDesign.objects.filter(is_active=True)
	home_page_title = None
	short_description = None
	home_page_description = None
	
	if home_page_content:
		for obj in home_page_content:
			home_page_title = obj.title
			short_description = obj.short_description
			home_page_description = obj.description

	last_projects = Project.objects.filter(is_active=True).order_by('-update')[:6]

	# for obj in last_projects:
	# 	prj_name = obj.name
	# 	prj_im

	# print('last_projects')

	context = {
		'title': title,
		'carousel_imgs':carousel_imgs,
		'home_page_title':home_page_title,
		'short_description':short_description,
		'home_page_description':home_page_description,
		'last_projects':last_projects,
	}

	return render(request, 'home/home.html', context)

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="google-site-verification" content="01WU9T_HXnjtw9nRbowhki36uugFUzlpEbbCSK75mtk" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Дизайн інтер'єру, сучасна гіпсова ліпнина ручної роботи - MISTECKIY DIM">
    <meta name="author" content="Igor Smolinskiy">
    <link rel="icon" href="{{ favicon.favicon.url }}">

    <title>{% block head_title %} MDIM {% endblock head_title %}</title>

    {% include 'head_css.html' %}

  </head>

  <body>

   <!--  <div class="preloader">
      <div class="loader"></div>
    </div> -->
    
    <div class="main-container">
    {% include 'navbar.html' %}

    {% block carousel %}

    {% endblock carousel %}

    {% block sub_nav_bar %}

    {% endblock sub_nav_bar %}

      <main role="main">

        {% block breadcrumb %}

        {% endblock breadcrumb %}

        <!-- Main jumbotron for a primary marketing message or call to action -->
        {% block jumbotron_content %}

        {% endblock jumbotron_content %}


        {% block content %}

        {% endblock content %}


      </main>

    {% include 'footer.html' %}
    </div>

   {% include 'js.html' %}

    <script async defer src="https://assets.pinterest.com/js/pinit.js"></script>

    {% block script %}

    {% endblock script %}

  </body>
</html>

templates/carousel.html
<!-- <div class="container-fluid">
  <div class="row">
    <div class="col-xs-12"> -->
      <div id="carousel" class="carousel slide carousel-max-height" data-ride="carousel">
        <div class="carousel-inner carousel-max-height">
          {% for carousel_img in carousel_imgs|slice:":5" %}
          {% if forloop.first %}
          <div class="carousel-item carousel-item-height active">
            <img class="w-100" src="{{ carousel_img.img.url }}" alt="{{ carousel_img.description|safe }}">
          </div>
          {% else %}
          <div class="carousel-item carousel-item-height">
            <img class="w-100" src="{{ carousel_img.img.url }}" alt="{{ carousel_img.description|safe }}">
          </div>
          {% endif %}
          {% endfor %}
          <a class="carousel-control-prev carousel-control-btn-height" href="#carousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next carousel-control-btn-height" href="#carousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
<!--     </div>
  </div>
</div> -->

templates/footer.html
<footer class="footer main-background-color">
	<div class="container">
		<nav class="navbar navbar-expand-md footer-nav">
			<a class="navbar-brand" href="/">Misteckiy Dim</a>
	  		<div class="d-none d-md-block d-xl-block ml-auto">
		      <ul class="navbar-nav">
		          <li class="nav-item">
		            <a class="nav-link" href="/">Головна</a>
		          </li>
		          <li class="nav-item">
		            <a class="nav-link" href="{% url 'about_us:about_us' %} ">Про нас</a>
		          </li>
		          <li class="nav-item">
		            <a class="nav-link" href="{% url 'projects:projects' %}">Проекти</a>
		          </li>
		          <li class="nav-item">
		            <a class="nav-link" href="{% url 'gallery:gallery' %}">Галерея</a>
		          </li>
		          <li class="nav-item">
		            <a class="nav-link" href="{% url 'prices:prices' %}">Ціни</a>
		          </li>
		          <!-- <li class="nav-item">
		            <a class="nav-link" href="#">Ліпнина</a>
		          </li> -->
		          <li class="nav-item">
		            <a class="nav-link" href="{% url 'contacts:contacts' %}">Контакти</a>
		          </li>
		        </ul>
		    </div>
		</nav>
	</div>
</footer>

templates/head_css.html
    {% load static %}
    <!-- Google fonts -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Pathway+Gothic+One&amp;subset=latin,latin-ext" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=El+Messiri&amp;subset=arabic,cyrillic" />

    <!-- International telephone input -->
    <link rel="stylesheet" href="{% static 'css/intlTelInput.css' %}">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

	<!-- Fancebox -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.3.5/jquery.fancybox.min.css" />

    <!-- Social icons -->
    <link rel="stylesheet" href="{% static 'css/social_icons.css' %}">

    <!-- International telephone input -->
    <link rel="stylesheet" href="{% static 'css/intlTelInput.css' %}">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <!-- Preloader -->
    <link rel="stylesheet" href="{% static 'css/nprogress.css' %}">
    

templates/home.html
{% extends 'base.html' %}

{% block head_title %}Welcome | {{ block.super }} {% endblock %}


{% block carousel %}

{% include 'carousel.html' %}

{% endblock carousel %}



{% block jumbotron_content %}

      <div class="jumbotron">
        <div class="container">
                  <!-- Example row of columns -->
        <div class="row">
          <div class="col-md-12">
            <div class="text-container">
                <h1>{{ home_page_title }}</h1>
                <div class="content hideContent">
                    <p>{{ home_page_description|safe }}</p>
                </div>
                <div class="show-more">
                    <button class="btn btn-secondary">Show more</button>
                </div>
            </div>

          </div>
        </div>

        <hr>
        </div>
      </div>

{% endblock jumbotron_content %}

{% block content %}


{% endblock content %}

templates/js.html
	{% load static %}
 	<!-- Bootstrap core JavaScript
    =================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
	<script
	  src="//code.jquery.com/jquery-3.3.1.min.js"
	  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
	  crossorigin="anonymous"></script>
	<script
	  src="//code.jquery.com/ui/1.12.1/jquery-ui.min.js"
	  integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
	  crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


    <script src="{% static 'js/custom.js' %}"></script>
	
	<!-- Preloader -->
    <script src="{% static 'js/nprogress.js' %}"></script>

    <script>
    	
        NProgress.configure({ showSpinner: false });
    	NProgress.start();

    	$(window).on ("load", function () {
    		setTimeout (function() {
    			NProgress.done();
	    		},
	    	700);
    	});

    </script>

     <!-- Fancybox -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.3.5/jquery.fancybox.min.js"></script>

templates/navbar.html
<div class="header main-background-color">
    <div class="navbar-header d-none d-md-block d-xl-block">
      <div class="container">
        <div class="row">

          <div class="col-md-4">
            <div class="header-social-networks social-networks text-left">
                <a href="https://www.instagram.com/misteckiy_dim" target="_blank" rel="nofollow">
                    <span class="icon-instagram"></span>
                </a>
                <a href="https://www.behance.net/md1m" target="_blank" rel="nofollow">
                    <span class="icon-behance"></span>
                </a>
                <a href="https://www.facebook.com/groups/misteckiy/" target="_blank" rel="nofollow">
                    <span class="icon-facebook"></span>
                </a>
                <a href="https://www.pinterest.com/misteckiy/" target="_blank" rel="nofollow">
                    <span class="icon-pinterest2"></span>
                </a>
                <a href="https://plus.google.com/110620023229417998858" target="_blank" rel="nofollow">
                    <span class="icon-google-plus"></span>
                </a>
                <a href="https://twitter.com/misteckiy" target="_blank" rel="nofollow">
                    <span class="icon-twitter"></span>
                </a>
              </div>
          </div>

          <div class="col-md-4">
            <div class="text-center"><a class="" href="/">Misteckiy Dim</a></div>
          </div>

          <div class="col-md-4">
            <div class="text-right">
              <ul class="langs list-unstyled">
                <li><span>Ua</span></li>
                <li>/</li>
                <li><a href="#en">En</a></li>
              </ul>
            </div>            
          </div>

        </div>

      </div>
    </div>
</div>

<nav class="navbar navbar-expand-md sticky-top navbar-light main-background-color">
  <div class="container">

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

     <a class="navbar-brand mx-auto d-md-none d-xl-none navbar-header-xs" href="/">Misteckiy Dim</a>

     <ul class="langs list-unstyled d-md-none d-xl-none">
        <li><span>Ua</span></li>
        <li>/</li>
        <li><a href="#en">En</a></li>
      </ul>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
        <ul class="navbar-nav main-menu mx-auto">
          <li class="nav-item">
            <a class="nav-link" href="/">Головна</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about_us:about_us' %} ">Про нас</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'projects:projects' %}">Проекти</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'gallery:gallery' %}">Галерея</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'prices:prices' %}">Ціни</a>
          </li>
      <!--     <li class="nav-item">
            <a class="nav-link" href="#">Ліпнина</a>
          </li> -->
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contacts:contacts' %}">Контакти</a>
          </li>

          <li class="nav-item d-md-none d-xl-none">
            <div class="social-networks">
              <a href="https://www.instagram.com/misteckiy_dim/" target="_blank" rel="nofollow">
                    <span class="icon-instagram"></span>
                </a>
                <a href="https://www.behance.net/md1m" target="_blank" rel="nofollow">
                    <span class="icon-behance"></span>
                </a>
                <a href="https://www.facebook.com/groups/misteckiy/" target="_blank" rel="nofollow">
                    <span class="icon-facebook"></span>
                </a>
                <a href="https://www.pinterest.com/misteckiy/" target="_blank" rel="nofollow">
                    <span class="icon-pinterest2"></span>
                </a>
                <a href="https://plus.google.com/110620023229417998858" target="_blank" rel="nofollow">
                    <span class="icon-google-plus"></span>
                </a>
                <a href="https://twitter.com/misteckiy" target="_blank" rel="nofollow">
                    <span class="icon-twitter"></span>
                </a>
            </div>
          </li>

        </ul>
      </div>
    </div>
  </nav>